# Generated by Django 5.1.7 on 2025-03-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='channels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.JSONField(default=list),
        ),
    ]
